# Makefile to build the MorphOS SDL tests

AR = ppc-morphos-ar
CC	= ppc-morphos-gcc-11
CFLAGS	= -noixemul -O2 -Wall -g -I../include -DHAVE_OPENGL
LIBS	= -L. -lSDL2test -L../src/core/morphos/devenv/lib/ -lSDL2 -noixemul -lm

TARGETS = \
	checkkeys \
	checkkeysthreads \
	controllermap \
	loopwave \
	loopwavequeue \
	testatomic \
	testaudiocapture \
	testaudiohotplug \
	testaudioinfo \
	testautomation \
	testbounds \
	testcustomcursor \
	testdisplayinfo \
	testdraw2 \
	testdrawchessboard \
	testdropfile \
	testerror \
	testfile \
	testfilesystem \
	testgamecontroller \
	testgeometry \
	testgesture \
	testgl2 \
	testgles \
	testgles2 \
	testhaptic \
	testhittesting \
	testhotplug \
	testiconv \
	testime \
	testintersections \
	testjoystick \
	testkeys \
	testloadso \
	testlocale \
	testlock \
	testmessage \
	testmouse \
	testmultiaudio \
	testoffscreen \
	testoverlay2 \
	testplatform \
	testpower \
	testqsort \
	testrelative \
	testrendercopyex \
	testrendertarget \
	testresample \
	testrumble \
	testscale \
	testsem \
	testshape \
	testsprite2 \
	testspriteminimal \
	teststreaming \
	testsurround \
	testthread \
	testtimer \
	testurl \
	testver \
	testviewport \
	testvulkan \
	testwm2 \
	testyuv \
	torturethread \
	testnative 
# testshader \

CSRCS = SDL_test_assert.c SDL_test_common.c SDL_test_compare.c \
        SDL_test_crc32.c SDL_test_font.c SDL_test_fuzzer.c SDL_test_harness.c \
        SDL_test_imageBlit.c SDL_test_imageBlitBlend.c SDL_test_imageFace.c \
        SDL_test_imagePrimitives.c SDL_test_imagePrimitivesBlend.c \
        SDL_test_log.c SDL_test_md5.c SDL_test_random.c SDL_test_memory.c
TESTLIB = libSDL2test.a
COBJS = $(addprefix ../src/test/, $(CSRCS:.c=.o))

all: $(TESTLIB) $(TARGETS)

$(TESTLIB): $(COBJS)
	$(AR) crvs $@ $^

checkkeys: checkkeys.o
	$(CC) -o $@ $^ $(LIBS)
	
checkkeysthreads: checkkeysthreads.o
	$(CC) -o $@ $^ $(LIBS)

controllermap: controllermap.o testutils.o
	$(CC) -o $@ $^ $(LIBS)

loopwave: loopwave.o testutils.o
	$(CC) -o $@ $^ $(LIBS)

loopwavequeue: loopwavequeue.o testutils.o
	$(CC) -o $@ $^ $(LIBS)

testresample: testresample.o
	$(CC) -o $@ $^ $(LIBS)

testaudioinfo: testaudioinfo.o
	$(CC) -o $@ $^ $(LIBS)

testautomation: testautomation.o \
		      testautomation_audio.o \
		      testautomation_clipboard.o \
		      testautomation_events.o \
			  testautomation_guid.o \
			  testautomation_joystick.o \
		      testautomation_keyboard.o \
		      testautomation_main.o \
			  testautomation_math.o \
		      testautomation_mouse.o \
		      testautomation_pixels.o \
		      testautomation_platform.o \
		      testautomation_rect.o \
		      testautomation_render.o \
		      testautomation_rwops.o \
		      testautomation_sdltest.o \
		      testautomation_stdlib.o \
		      testautomation_subsystems.o \
		      testautomation_surface.o \
		      testautomation_syswm.o \
		      testautomation_timer.o \
		      testautomation_video.o \
		      testautomation_hints.o
	$(CC) -o $@ $^ $(LIBS) 

testmultiaudio: testmultiaudio.o testutils.o
	$(CC) -o $@ $^ $(LIBS)

testmouse: testmouse.o
	$(CC) -o $@ $^ $(LIBS)

testaudiohotplug: testaudiohotplug.o testutils.o
	$(CC) -o $@ $^ $(LIBS)

testaudiocapture: testaudiocapture.o
	$(CC) -o $@ $^ $(LIBS)

testatomic: testatomic.o
	$(CC) -o $@ $^ $(LIBS)

testintersections: testintersections.o
	$(CC) -o $@ $^ $(LIBS)

testrelative: testrelative.o
	$(CC) -o $@ $^ $(LIBS)

testhittesting: testhittesting.o
	$(CC) -o $@ $^ $(LIBS)

testdraw2: testdraw2.o
	$(CC) -o $@ $^ $(LIBS)

testdrawchessboard: testdrawchessboard.o
	$(CC) -o $@ $^ $(LIBS)

testdropfile: testdropfile.o
	$(CC) -o $@ $^ $(LIBS)

testerror: testerror.o
	$(CC) -o $@ $^ $(LIBS)

testfile: testfile.o
	$(CC) -o $@ $^ $(LIBS)

testgamecontroller: testgamecontroller.o testutils.o
	$(CC) -o $@ $^ $(LIBS)
 
testgeometry: testgeometry.o testutils.o
	$(CC) -o $@ $^ $(LIBS)

testgesture: testgesture.o
	$(CC) -o $@ $^ $(LIBS)
 
testgl2: testgl2.o
	$(CC) -o $@ $^ $(LIBS)

testgles: testgles.o
	$(CC) -o $@ $^ $(LIBS)

testgles2: testgles2.o
	$(CC) -o $@ $^ $(LIBS)

testhaptic: testhaptic.o
	$(CC) -o $@ $^ $(LIBS)

testhotplug: testhotplug.o
	$(CC) -o $@ $^ $(LIBS)

testrumble: testrumble.o
	$(CC) -o $@ $^ $(LIBS)

testthread: testthread.o
	$(CC) -o $@ $^ $(LIBS)

testiconv: testiconv.o testutils.o
	$(CC) -o $@ $^ $(LIBS)

testime: testime.o testutils.o
	$(CC) -o $@ $^ $(LIBS)

testjoystick: testjoystick.o
	$(CC) -o $@ $^ $(LIBS)

testkeys: testkeys.o
	$(CC) -o $@ $^ $(LIBS)

testlocale: testlocale.o
	$(CC) -o $@ $^ $(LIBS)
	
testloadso: testloadso.o
	$(CC) -o $@ $^ $(LIBS)
	
testsurround: testsurround.o
	$(CC) -o $@ $^ $(LIBS)
	
testlock: testlock.o
	$(CC) -o $@ $^ $(LIBS)

testnative: testnative.o testnativemorphos.o testutils.o
	$(CC) -o $@ $^ $(LIBS)

testoffscreen: testoffscreen.o
	$(CC) -o $@ $^ $(LIBS)

testoverlay2: testoverlay2.o testyuv_cvt.o testutils.o
	$(CC) -o $@ $^ $(LIBS)

testplatform: testplatform.o
	$(CC) -o $@ $^ $(LIBS)

testpower: testpower.o
	$(CC) -o $@ $^ $(LIBS)

testfilesystem: testfilesystem.o
	$(CC) -o $@ $^ $(LIBS)

testrendertarget: testrendertarget.o testutils.o
	$(CC) -o $@ $^ $(LIBS)

testscale: testscale.o testutils.o
	$(CC) -o $@ $^ $(LIBS)

testsem: testsem.o
	$(CC) -o $@ $^ $(LIBS)

testsensor: testsensor.o
	$(CC) -o $@ $^ $(LIBS)

testshader: testshader.o
	$(CC) -o $@ $^ $(LIBS)

testshape: testshape.o
	$(CC) -o $@ $^ $(LIBS)

testsprite2: testsprite2.o testutils.o
	$(CC) -o $@ $^ $(LIBS)

testspriteminimal: testspriteminimal.o testutils.o
	$(CC) -o $@ $^ $(LIBS)

teststreaming: teststreaming.o testutils.o
	$(CC) -o $@ $^ $(LIBS)

testtimer: testtimer.o
	$(CC) -o $@ $^ $(LIBS)

testver: testver.o
	$(CC) -o $@ $^ $(LIBS)

testviewport: testviewport.o testutils.o
	$(CC) -o $@ $^ $(LIBS)

testwm2: testwm2.o
	$(CC) -o $@ $^ $(LIBS)

testyuv: testyuv.o testyuv_cvt.o
	$(CC) -o $@ $^ $(LIBS)

torturethread: torturethread.o
	$(CC) -o $@ $^ $(LIBS)

testrendercopyex: testrendercopyex.o testutils.o
	$(CC) -o $@ $^ $(LIBS)

testmessage: testmessage.o
	$(CC) -o $@ $^ $(LIBS)

testdisplayinfo: testdisplayinfo.o
	$(CC) -o $@ $^ $(LIBS)

testqsort: testqsort.o
	$(CC) -o $@ $^ $(LIBS)

testbounds: testbounds.o
	$(CC) -o $@ $^ $(LIBS)

testcustomcursor: testcustomcursor.o
	$(CC) -o $@ $^ $(LIBS)

testvulkan: testvulkan.o
	$(CC) -o $@ $^ $(LIBS)

testurl: testurl.o
	$(CC) -o $@ $^ $(LIBS)

clean:
	rm -f $(TARGETS) *.o $(COBJS) $(TESTLIB)
