#!/bin/sh

prefix=/usr/local
exec_prefix=${prefix}
exec_prefix_set=no

libmode=``

usage="\
Usage: sdl2-config [--prefix[=DIR]] [--exec-prefix[=DIR]] [--version] [--libs] [--cflags]"

if test $# -eq 0; then
      echo "${usage}" 1>&2
      exit 1
fi

while test $# -gt 0; do
  case "$1" in
  -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
  *) optarg= ;;
  esac

  case $1 in
    --prefix=*)
      prefix=$optarg
      if test $exec_prefix_set = no ; then
        exec_prefix=$optarg
      fi
      ;;
    --prefix)
      echo $prefix
      ;;
    --exec-prefix=*)
      exec_prefix=$optarg
      exec_prefix_set=yes
      ;;
    --exec-prefix)
      echo $exec_prefix
      ;;
    --version)
      echo 2.30.0
      ;;
    --cflags)
     	echo -noixemul -I${prefix}/include/SDL2
      ;;
    --libs|--static-libs)
      libdirs="-L${exec_prefix}/lib "
      echo  $libdirs -noixemul -lSDL2 -lc -lm
      ;;
    *)
      echo "${usage}" 1>&2
      exit 1
      ;;
  esac
  shift
done
